services:
  backend:
    build: ./backend
    ports:
      - "3050:3050"  # El puerto 3050 está expuesto a la máquina host
    env_file:
      - ./backend/src/config/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # El frontend se expone en el puerto 3000
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: alvaro
      POSTGRES_PASSWORD: rdr123
      POSTGRES_DB: carniceria
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: